title: openLimits
logo: logo.svg
description: A Rust high performance cryptocurrency trading API with support for multiple exchanges and language wrappers.
google_analytics: UA-115551927-13
theme: jekyll-theme-minimal
