name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  clippy_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
    - name: rust-clippy-check
      with:
        toolchain: nightly
        components: rustfmt, clippy
        override: true
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features

  rustfmt_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
    - name: rust-clippy-check
      with:
        toolchain: nightly
        components: rustfmt
        override: true
    - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  name: Security audit
    on:
      schedule:
        - cron: '0 0 * * *'
    jobs:
      audit:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions-rs/audit-check@v1
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
